description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
  # firebase_core: ^1.15.0
  # cloud_firestore: ^3.1.13
  # firebase_auth: ^3.3.15
  # firebase_app_check: ^0.0.6
  # firebase_database: ^9.0.12
  # cloud_functions: ^3.2.13
  # firebase_storage: ^10.2.13
  # firebase_analytics: ^9.1.6
  # resize: ^1.0.0
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Quicksand"
      fonts: 
        - 
          asset: "fonts/Quicksand-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Quicksand-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Quicksand-600.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/Quicksand-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Mulish"
      fonts: 
        - 
          asset: "fonts/Mulish-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Montserrat"
      fonts: 
        - 
          asset: "fonts/Montserrat-600.ttf"
          style: "normal"
          weight: 600
  uses-material-design: true
