import 'package:flutter/material.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/GeneratedTotalVolumn6000lbWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/Generated5Widget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/GeneratedYourScheduleWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/GeneratedExercise2DumbellFlyerWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/Generated5000lbWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/Generated5Widget1.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/GeneratedEXITWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/GeneratedSetWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/GeneratedChestDayWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/Generated1000lbWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/GeneratedExercise1BenchPressWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/GeneratedRepetitionWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/Generated200lbWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/GeneratedWeightWidget2.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/Generated10Widget1.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/GeneratedVolumnWidget1.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/GeneratedSetWidget1.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/GeneratedVolumnWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/GeneratedGroupWidget327.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/Generated10Widget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/GeneratedCFA_RunningHistoryeditWidget1.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/GeneratedRepetitionWidget1.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/Generated100lbWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/GeneratedWeightWidget1.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistoryeditwidget/generated/GeneratedChat_altWidget9.dart';

/* Frame CFA_ Running-History edit
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCFA_RunningHistoryeditWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 814.0,
                child: GeneratedCFA_RunningHistoryeditWidget1(),
              ),
              Positioned(
                left: 139.0,
                top: 32.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 27.0,
                child: GeneratedChestDayWidget(),
              ),
              Positioned(
                left: 272.0,
                top: 32.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 30.0,
                child: GeneratedEXITWidget(),
              ),
              Positioned(
                left: 126.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 25.0,
                child: GeneratedYourScheduleWidget(),
              ),
              Positioned(
                left: 74.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 23.0,
                child: GeneratedWeightWidget1(),
              ),
              Positioned(
                left: 143.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 23.0,
                child: GeneratedRepetitionWidget(),
              ),
              Positioned(
                left: 230.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 23.0,
                child: GeneratedSetWidget(),
              ),
              Positioned(
                left: 276.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 23.0,
                child: GeneratedVolumnWidget(),
              ),
              Positioned(
                left: 78.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 20.0,
                child: Generated100lbWidget(),
              ),
              Positioned(
                left: 163.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 19.0,
                height: 23.0,
                child: Generated10Widget(),
              ),
              Positioned(
                left: 236.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 23.0,
                child: Generated5Widget(),
              ),
              Positioned(
                left: 276.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 20.0,
                child: Generated5000lbWidget(),
              ),
              Positioned(
                left: 77.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 23.0,
                child: GeneratedWeightWidget2(),
              ),
              Positioned(
                left: 146.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 23.0,
                child: GeneratedRepetitionWidget1(),
              ),
              Positioned(
                left: 233.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 23.0,
                child: GeneratedSetWidget1(),
              ),
              Positioned(
                left: 279.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 23.0,
                child: GeneratedVolumnWidget1(),
              ),
              Positioned(
                left: 81.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 20.0,
                child: Generated200lbWidget(),
              ),
              Positioned(
                left: 166.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 19.0,
                height: 23.0,
                child: Generated10Widget1(),
              ),
              Positioned(
                left: 239.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 23.0,
                child: Generated5Widget1(),
              ),
              Positioned(
                left: 279.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 20.0,
                child: Generated1000lbWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 309.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 22.0,
                child: GeneratedExercise1BenchPressWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 22.0,
                child: GeneratedExercise2DumbellFlyerWidget(),
              ),
              Positioned(
                left: 84.0,
                top: 644.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 27.0,
                child: GeneratedTotalVolumn6000lbWidget(),
              ),
              Positioned(
                left: 141.0,
                top: 766.0,
                right: null,
                bottom: null,
                width: 23.441999435424805,
                height: 24.0,
                child: GeneratedGroupWidget327(),
              ),
              Positioned(
                left: 215.0,
                top: 765.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 26.0,
                child: GeneratedChat_altWidget9(),
              )
            ]),
      ),
    ));
  }
}
