import 'package:flutter/material.dart';
import 'package:flutterapp/fitapp/generatedarticlefootwidget/generated/GeneratedGroupWidget193.dart';
import 'package:flutterapp/fitapp/generatedarticlefootwidget/generated/GeneratedPremiumWidget5.dart';
import 'package:flutterapp/fitapp/generatedarticlefootwidget/generated/GeneratedGroupWidget192.dart';
import 'package:flutterapp/fitapp/generatedarticlefootwidget/generated/GeneratedCFA_ExercusesWidget3.dart';
import 'package:flutterapp/fitapp/generatedarticlefootwidget/generated/GeneratedChat_altWidget7.dart';

/* Frame Article foot
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedArticlefootWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 844.1279907226562,
                child: GeneratedCFA_ExercusesWidget3(),
              ),
              Positioned(
                left: 300.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 23.0,
                child: GeneratedPremiumWidget5(),
              ),
              Positioned(
                left: 304.0,
                top: 98.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 21.0,
                child: GeneratedGroupWidget192(),
              ),
              Positioned(
                left: 128.0,
                top: 762.0,
                right: null,
                bottom: null,
                width: 23.441999435424805,
                height: 24.0,
                child: GeneratedGroupWidget193(),
              ),
              Positioned(
                left: 202.0,
                top: 761.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 26.0,
                child: GeneratedChat_altWidget7(),
              )
            ]),
      ),
    ));
  }
}
