import 'package:flutter/material.dart';
import 'package:flutterapp/fitapp/generatedonboarding1widget/generated/GeneratedOnboarding1Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fitapp/generatedonboarding1widget/generated/GeneratedGroupWidget223.dart';
import 'package:flutterapp/fitapp/generatedonboarding1widget/generated/GeneratedTrackyourworkoutWidget.dart';
import 'package:flutter/foundation.dart' show kIsWeb;

/* Frame Onboarding 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnboarding1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 812.0,
                  child: GeneratedOnboarding1Widget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: null,
                  right: 0.0,
                  bottom: null,
                  width: null,
                  height: 32.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: -341.00,
                      z: 0,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.756698974609375;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.034666666666666665,
                              y: 0,
                              z: 0,
                              child: Container(
                                width: width,
                                child: GeneratedTrackyourworkoutWidget(),
                              ))
                        ]);
                      })),
                ),
                Positioned(
                  left: 19.0,
                  top: 719.0,
                  right: null,
                  bottom: null,
                  width: 320.0,
                  height: 50.0,
                  child: GeneratedGroupWidget223(),
                )
              ]),
        ),
      ),
    ));
  }
}
