import 'package:flutter/material.dart';
import 'package:flutterapp/fitapp/generatedbreakfastwidget1/generated/GeneratedChat_altWidget3.dart';
import 'package:flutterapp/fitapp/generatedbreakfastwidget1/generated/GeneratedQuickAddWidget.dart';
import 'package:flutterapp/fitapp/generatedbreakfastwidget1/generated/GeneratedGroupWidget30.dart';
import 'package:flutterapp/fitapp/generatedbreakfastwidget1/generated/GeneratedGroupWidget22.dart';
import 'package:flutterapp/fitapp/generatedbreakfastwidget1/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/fitapp/generatedbreakfastwidget1/generated/GeneratedScanBarcodeWidget.dart';
import 'package:flutterapp/fitapp/generatedbreakfastwidget1/generated/GeneratedGroupWidget28.dart';
import 'package:flutterapp/fitapp/generatedbreakfastwidget1/generated/GeneratedGroupWidget26.dart';
import 'package:flutterapp/fitapp/generatedbreakfastwidget1/generated/GeneratedGroupWidget25.dart';
import 'package:flutterapp/fitapp/generatedbreakfastwidget1/generated/GeneratedScanMealWidget.dart';
import 'package:flutterapp/fitapp/generatedbreakfastwidget1/generated/GeneratedGroupWidget32.dart';
import 'package:flutterapp/fitapp/generatedbreakfastwidget1/generated/GeneratedShapeWidget31.dart';

/* Frame breakfast
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBreakfastWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 812.0,
              child: GeneratedGroup8Widget(),
            ),
            Positioned(
              left: 24.0,
              top: 489.0,
              right: null,
              bottom: null,
              width: 329.0,
              height: 50.0,
              child: GeneratedShapeWidget31(),
            ),
            Positioned(
              left: 23.0,
              top: 294.0,
              right: null,
              bottom: null,
              width: 330.0,
              height: 245.0,
              child: GeneratedGroupWidget22(),
            ),
            Positioned(
              left: 57.0,
              top: 37.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 16.799999237060547,
              child: GeneratedGroupWidget25(),
            ),
            Positioned(
              left: 10.0,
              top: 161.0,
              right: null,
              bottom: null,
              width: 113.0,
              height: 33.0,
              child: GeneratedGroupWidget26(),
            ),
            Positioned(
              left: 130.0,
              top: 160.0,
              right: null,
              bottom: null,
              width: 114.0,
              height: 33.0,
              child: GeneratedGroupWidget28(),
            ),
            Positioned(
              left: 250.0,
              top: 160.0,
              right: null,
              bottom: null,
              width: 114.0,
              height: 33.0,
              child: GeneratedGroupWidget30(),
            ),
            Positioned(
              left: 29.0,
              top: 166.0,
              right: null,
              bottom: null,
              width: 75.0,
              height: 16.0,
              child: GeneratedScanMealWidget(),
            ),
            Positioned(
              left: 142.0,
              top: 166.0,
              right: null,
              bottom: null,
              width: 94.0,
              height: 20.0,
              child: GeneratedScanBarcodeWidget(),
            ),
            Positioned(
              left: 272.0,
              top: 166.0,
              right: null,
              bottom: null,
              width: 69.0,
              height: 20.0,
              child: GeneratedQuickAddWidget(),
            ),
            Positioned(
              left: 138.0,
              top: 764.0,
              right: null,
              bottom: null,
              width: 23.441999435424805,
              height: 24.0,
              child: GeneratedGroupWidget32(),
            ),
            Positioned(
              left: 212.0,
              top: 763.0,
              right: null,
              bottom: null,
              width: 26.0,
              height: 26.0,
              child: GeneratedChat_altWidget3(),
            )
          ]),
    ));
  }
}
