import 'package:flutter/material.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget2/generated/GeneratedGoodFoodExerciseRemainingWidget1.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget2/generated/GeneratedCFA_RunningHistoryWidget3.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget2/generated/GeneratedChat_altWidget2.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget2/generated/GeneratedCaloriesWidget1.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget2/generated/GeneratedChat_altWidget1.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget2/generated/GeneratedPremiumWidget1.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget2/generated/GeneratedCalendar_duotoneWidget1.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget2/generated/Generated25008001501850Widget1.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget2/generated/GeneratedGroupWidget17.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget2/generated/GeneratedGroupWidget9.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget2/generated/GeneratedMar15Widget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget2/generated/GeneratedGroupWidget15.dart';

/* Frame CFA_Running-History
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCFA_RunningHistoryWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedCFA_RunningHistoryWidget3(),
              ),
              Positioned(
                left: 149.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 30.0,
                child: GeneratedCaloriesWidget1(),
              ),
              Positioned(
                left: 40.0,
                top: 166.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 27.0,
                child: Generated25008001501850Widget1(),
              ),
              Positioned(
                left: 31.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 20.0,
                child: GeneratedGoodFoodExerciseRemainingWidget1(),
              ),
              Positioned(
                left: 155.0,
                top: 257.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 25.0,
                child: GeneratedMar15Widget(),
              ),
              Positioned(
                left: 293.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 23.0,
                child: GeneratedPremiumWidget1(),
              ),
              Positioned(
                left: 22.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 381.0,
                child: GeneratedGroupWidget9(),
              ),
              Positioned(
                left: 140.0,
                top: 764.0,
                right: null,
                bottom: null,
                width: 23.441999435424805,
                height: 24.0,
                child: GeneratedGroupWidget15(),
              ),
              Positioned(
                left: 214.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 26.0,
                child: GeneratedChat_altWidget1(),
              ),
              Positioned(
                left: 140.0,
                top: 764.0,
                right: null,
                bottom: null,
                width: 23.441999435424805,
                height: 24.0,
                child: GeneratedGroupWidget17(),
              ),
              Positioned(
                left: 214.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 26.0,
                child: GeneratedChat_altWidget2(),
              ),
              Positioned(
                left: 230.0,
                top: 254.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 29.0,
                child: GeneratedCalendar_duotoneWidget1(),
              )
            ]),
      ),
    ));
  }
}
