import 'package:flutter/material.dart';
import 'package:flutterapp/fitapp/generatedcfa_register3widget/generated/GeneratedGroupWidget280.dart';
import 'package:flutterapp/fitapp/generatedcfa_register3widget/generated/GeneratedGroupWidget268.dart';
import 'package:flutterapp/fitapp/generatedcfa_register3widget/generated/GeneratedGroupWidget265.dart';
import 'package:flutterapp/fitapp/generatedcfa_register3widget/generated/GeneratedGroupWidget263.dart';
import 'package:flutterapp/fitapp/generatedcfa_register3widget/generated/GeneratedGroupWidget284.dart';
import 'package:flutterapp/fitapp/generatedcfa_register3widget/generated/GeneratedGroupWidget283.dart';
import 'package:flutterapp/fitapp/generatedcfa_register3widget/generated/GeneratedGroupWidget290.dart';
import 'package:flutterapp/fitapp/generatedcfa_register3widget/generated/GeneratedGroupWidget286.dart';
import 'package:flutterapp/fitapp/generatedcfa_register3widget/generated/GeneratedGroupWidget260.dart';
import 'package:flutterapp/fitapp/generatedcfa_register3widget/generated/GeneratedCFA_SelectyourfitnesslevelWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_register3widget/generated/GeneratedGroupWidget270.dart';
import 'package:flutterapp/fitapp/generatedcfa_register3widget/generated/GeneratedGroupWidget277.dart';
import 'package:flutterapp/fitapp/generatedcfa_register3widget/generated/GeneratedGroupWidget256.dart';
import 'package:flutterapp/fitapp/generatedcfa_register3widget/generated/GeneratedGroupWidget275.dart';
import 'package:flutterapp/fitapp/generatedcfa_register3widget/generated/GeneratedGroupWidget273.dart';

/* Frame CFA_register3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCFA_register3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedCFA_SelectyourfitnesslevelWidget(),
              ),
              Positioned(
                left: 216.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 30.0,
                child: GeneratedGroupWidget256(),
              ),
              Positioned(
                left: 264.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 40.0,
                child: GeneratedGroupWidget260(),
              ),
              Positioned(
                left: 26.0,
                top: 303.0,
                right: null,
                bottom: null,
                width: 321.5,
                height: 65.0,
                child: GeneratedGroupWidget263(),
              ),
              Positioned(
                left: 237.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 40.0,
                child: GeneratedGroupWidget265(),
              ),
              Positioned(
                left: 24.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 321.5,
                height: 65.0,
                child: GeneratedGroupWidget268(),
              ),
              Positioned(
                left: 264.0,
                top: 384.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 40.0,
                child: GeneratedGroupWidget270(),
              ),
              Positioned(
                left: 25.0,
                top: 433.0,
                right: null,
                bottom: null,
                width: 321.5,
                height: 65.0,
                child: GeneratedGroupWidget273(),
              ),
              Positioned(
                left: 23.499988555908203,
                top: 498.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 65.0000228881836,
                child: GeneratedGroupWidget275(),
              ),
              Positioned(
                left: 243.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 40.0,
                child: GeneratedGroupWidget277(),
              ),
              Positioned(
                left: 177.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 40.0,
                child: GeneratedGroupWidget280(),
              ),
              Positioned(
                left: 284.0,
                top: 522.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 40.0,
                child: GeneratedGroupWidget283(),
              ),
              Positioned(
                left: 23.0,
                top: 563.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 65.0000228881836,
                child: GeneratedGroupWidget284(),
              ),
              Positioned(
                left: 215.0,
                top: 583.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 30.0,
                child: GeneratedGroupWidget286(),
              ),
              Positioned(
                left: 142.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 25.0,
                child: GeneratedGroupWidget290(),
              )
            ]),
      ),
    ));
  }
}
