import 'package:flutter/material.dart';
import 'package:flutterapp/fitapp/generatedcfa_loginwidget/generated/GeneratedGroupWidget345.dart';
import 'package:flutterapp/fitapp/generatedcfa_loginwidget/generated/GeneratedGroupWidget346.dart';
import 'package:flutterapp/fitapp/generatedcfa_loginwidget/generated/GeneratedGroupWidget342.dart';
import 'package:flutterapp/fitapp/generatedcfa_loginwidget/generated/GeneratedCFA_LoginWidget1.dart';

/* Frame CFA_Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCFA_LoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(fit: StackFit.expand, alignment: Alignment.center, overflow: Overflow.visible, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 812.0,
            child: GeneratedCFA_LoginWidget1(),
          ),
          Positioned(
            left: 25.0,
            top: 727.0,
            right: null,
            bottom: null,
            width: 320.0,
            height: 50.0,
            child: GeneratedGroupWidget342(),
          ),
          Positioned(
            left: 18.0,
            top: 699.0,
            right: null,
            bottom: null,
            width: 170.0,
            height: 23.0,
            child: GeneratedGroupWidget345(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 320.0,
            height: 50.0,
            child: GeneratedGroupWidget346(),
          )
        ]),
      ),
    ));
  }
}
