import 'package:flutter/material.dart';
import 'package:flutterapp/fitapp/generatedaddmealplanwidget/generated/GeneratedCFA_2RunningCalories2Widget.dart';
import 'package:flutterapp/fitapp/generatedaddmealplanwidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/fitapp/generatedaddmealplanwidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/fitapp/generatedaddmealplanwidget/generated/GeneratedCFA_TraningPlanWater1Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fitapp/generatedaddmealplanwidget/generated/GeneratedDensityWidget.dart';
import 'package:flutterapp/fitapp/generatedaddmealplanwidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/fitapp/generatedaddmealplanwidget/generated/GeneratedGroupWidget368.dart';
import 'package:flutterapp/fitapp/generatedaddmealplanwidget/generated/GeneratedSaveWidget.dart';

/* Frame Add meal plan
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddmealplanWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 810.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 812.0,
                child: GeneratedCFA_TraningPlanWater1Widget(),
              ),
              Positioned(
                left: 98.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 228.75,
                child: GeneratedGroupWidget368(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: null,
                width: null,
                height: 25.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -283.50,
                    z: 0,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      final double width =
                          constraints.maxWidth * 0.35733333333333334;

                      return Stack(children: [
                        TransformHelper.translate(
                            x: constraints.maxWidth * 0.33866666666666667,
                            y: 0,
                            z: 0,
                            child: Container(
                              width: width,
                              child: GeneratedDensityWidget(),
                            ))
                      ]);
                    })),
              ),
              Positioned(
                left: null,
                top: 750.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 29.0,
                child: TransformHelper.translate(
                    x: -2.50, y: 0.00, z: 0, child: GeneratedSaveWidget()),
              ),
              Positioned(
                left: 39.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 210.0,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 321.5,
                height: 54.99997329711914,
                child: GeneratedGroup5Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 649.0,
                right: null,
                bottom: null,
                width: 321.5,
                height: 54.99997329711914,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 2654.0,
                top: -2.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedCFA_2RunningCalories2Widget(),
              )
            ]),
      ),
    ));
  }
}
