import 'package:flutter/material.dart';
import 'package:flutterapp/fitapp/generatedarticlefullwidget/generated/GeneratedCFA_ExercusesWidget.dart';
import 'package:flutterapp/fitapp/generatedarticlefullwidget/generated/GeneratedGroupWidget73.dart';
import 'package:flutterapp/fitapp/generatedarticlefullwidget/generated/GeneratedChat_altWidget4.dart';
import 'package:flutterapp/fitapp/generatedarticlefullwidget/generated/GeneratedPremiumWidget2.dart';

/* Frame Article full
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedArticlefullWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(fit: StackFit.expand, alignment: Alignment.center, overflow: Overflow.visible, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 376.0,
            height: 844.1279907226562,
            child: GeneratedCFA_ExercusesWidget(),
          ),
          Positioned(
            left: 298.0,
            top: 51.0,
            right: null,
            bottom: null,
            width: 65.0,
            height: 23.0,
            child: GeneratedPremiumWidget2(),
          ),
          Positioned(
            left: 138.0,
            top: 761.0,
            right: null,
            bottom: null,
            width: 23.441999435424805,
            height: 24.0,
            child: GeneratedGroupWidget73(),
          ),
          Positioned(
            left: 212.0,
            top: 761.0,
            right: null,
            bottom: null,
            width: 26.0,
            height: 26.0,
            child: GeneratedChat_altWidget4(),
          ),
        ]),
      ),
    ));
  }
}
