import 'package:flutter/material.dart';
import 'package:flutterapp/fitapp/generatedpremiummembershipwidget/generated/GeneratedAdvancedActivityTrackingWidget.dart';
import 'package:flutterapp/fitapp/generatedpremiummembershipwidget/generated/GeneratedCustomizedTrainingAdviceWidget.dart';
import 'package:flutterapp/fitapp/generatedpremiummembershipwidget/generated/GeneratedShapeWidget262.dart';
import 'package:flutterapp/fitapp/generatedpremiummembershipwidget/generated/Generated\$1499monthWidget.dart';
import 'package:flutterapp/fitapp/generatedpremiummembershipwidget/generated/GeneratedGroupWidget452.dart';
import 'package:flutterapp/fitapp/generatedpremiummembershipwidget/generated/GeneratedWorkoutWidget.dart';
import 'package:flutterapp/fitapp/generatedpremiummembershipwidget/generated/GeneratedChat_altWidget10.dart';
import 'package:flutterapp/fitapp/generatedpremiummembershipwidget/generated/Generated\$11999yearWidget.dart';
import 'package:flutterapp/fitapp/generatedpremiummembershipwidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/fitapp/generatedpremiummembershipwidget/generated/GeneratedGroupWidget445.dart';
import 'package:flutterapp/fitapp/generatedpremiummembershipwidget/generated/GeneratedEasytoSucceedWidget.dart';
import 'package:flutterapp/fitapp/generatedpremiummembershipwidget/generated/GeneratedInterfaceStarWidget3.dart';
import 'package:flutterapp/fitapp/generatedpremiummembershipwidget/generated/GeneratedInterfaceStarWidget.dart';
import 'package:flutterapp/fitapp/generatedpremiummembershipwidget/generated/GeneratedPersonalMealPlanWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fitapp/generatedpremiummembershipwidget/generated/GeneratedInterfaceStarWidget2.dart';
import 'package:flutterapp/fitapp/generatedpremiummembershipwidget/generated/GeneratedInterfaceStarWidget1.dart';
import 'package:flutterapp/fitapp/generatedpremiummembershipwidget/generated/GeneratedCFA_TraningPlanDetailsWidget.dart';

/* Frame Premium Membership
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPremiumMembershipWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedCFA_TraningPlanDetailsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: null,
                width: null,
                height: 30.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -355.00,
                    z: 0,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      final double width =
                          constraints.maxWidth * 0.24266666666666667;

                      return Stack(children: [
                        TransformHelper.translate(
                            x: constraints.maxWidth * 0.384,
                            y: 0,
                            z: 0,
                            child: Container(
                              width: width,
                              child: GeneratedWorkoutWidget(),
                            ))
                      ]);
                    })),
              ),
              Positioned(
                left: 34.0,
                top: 122.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedInterfaceStarWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 198.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedInterfaceStarWidget1(),
              ),
              Positioned(
                left: 34.0,
                top: 274.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedInterfaceStarWidget2(),
              ),
              Positioned(
                left: 34.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedInterfaceStarWidget3(),
              ),
              Positioned(
                left: 98.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 24.0,
                child: GeneratedEasytoSucceedWidget(),
              ),
              Positioned(
                left: 98.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 24.0,
                child: GeneratedCustomizedTrainingAdviceWidget(),
              ),
              Positioned(
                left: 98.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 24.0,
                child: GeneratedPersonalMealPlanWidget(),
              ),
              Positioned(
                left: 98.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 257.0,
                height: 24.0,
                child: GeneratedAdvancedActivityTrackingWidget(),
              ),
              Positioned(
                left: 344.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 165.0,
                child: GeneratedGroupWidget445(),
              ),
              Positioned(
                left: 60.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 0.0,
                child: GeneratedShapeWidget262(),
              ),
              Positioned(
                left: 123.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 24.0,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 235.0,
                top: 556.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 22.0,
                child: Generated$1499monthWidget(),
              ),
              Positioned(
                left: 65.0,
                top: 539.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 22.0,
                child: Generated$11999yearWidget(),
              ),
              Positioned(
                left: 138.0,
                top: 764.0,
                right: null,
                bottom: null,
                width: 23.441999435424805,
                height: 24.0,
                child: GeneratedGroupWidget452(),
              ),
              Positioned(
                left: 212.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 26.0,
                child: GeneratedChat_altWidget10(),
              )
            ]),
      ),
    ));
  }
}
