import 'package:flutter/material.dart';
import 'package:flutterapp/fitapp/generatedarticlebodywidget/generated/GeneratedCFA_ExercusesWidget1.dart';
import 'package:flutterapp/fitapp/generatedarticlebodywidget/generated/GeneratedShapeWidget48.dart';
import 'package:flutterapp/fitapp/generatedarticlebodywidget/generated/GeneratedChat_altWidget5.dart';
import 'package:flutterapp/fitapp/generatedarticlebodywidget/generated/GeneratedGroupWidget113.dart';
import 'package:flutterapp/fitapp/generatedarticlebodywidget/generated/GeneratedPremiumWidget3.dart';

/* Frame Article body
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedArticlebodyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 844.1279907226562,
                child: GeneratedCFA_ExercusesWidget1(),
              ),
              Positioned(
                left: 302.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 0.0,
                child: GeneratedShapeWidget48(),
              ),
              Positioned(
                left: 298.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 23.0,
                child: GeneratedPremiumWidget3(),
              ),
              Positioned(
                left: 138.0,
                top: 767.0,
                right: null,
                bottom: null,
                width: 23.441999435424805,
                height: 24.0,
                child: GeneratedGroupWidget113(),
              ),
              Positioned(
                left: 212.0,
                top: 766.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 26.0,
                child: GeneratedChat_altWidget5(),
              )
            ]),
      ),
    ));
  }
}
