import 'package:flutter/material.dart';
import 'package:flutterapp/fitapp/generatedarticle_detailswidget/generated/GeneratedChat_altWidget8.dart';
import 'package:flutterapp/fitapp/generatedarticle_detailswidget/generated/GeneratedCFA_TipsDetailsWidget.dart';
import 'package:flutterapp/fitapp/generatedarticle_detailswidget/generated/GeneratedGroupWidget244.dart';

/* Frame Article_details
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedArticle_detailsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedCFA_TipsDetailsWidget(),
              ),
              Positioned(
                left: 136.0,
                top: 764.0,
                right: null,
                bottom: null,
                width: 23.441999435424805,
                height: 24.0,
                child: GeneratedGroupWidget244(),
              ),
              Positioned(
                left: 210.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 26.0,
                child: GeneratedChat_altWidget8(),
              )
            ]),
      ),
    ));
  }
}
