import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fitapp/generatedonboarding2widget/generated/GeneratedOnboarding2Widget1.dart';
import 'package:flutterapp/fitapp/generatedonboarding2widget/generated/GeneratedTrackyourworkoutWidget1.dart';

/* Frame Onboarding 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnboarding2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedOnboarding2Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: null,
                width: null,
                height: 32.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -311.00,
                    z: 0,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      final double width =
                          constraints.maxWidth * 0.756698974609375;

                      return Stack(children: [
                        TransformHelper.translate(
                            x: constraints.maxWidth * 0.33866666666666667,
                            y: 0,
                            z: 0,
                            child: Container(
                              width: width,
                              child: GeneratedTrackyourworkoutWidget1(),
                            ))
                      ]);
                    })),
              )
            ]),
      ),
    ));
  }
}
