import 'package:flutter/material.dart';
import 'package:flutterapp/fitapp/generatedcoverwidget1/generated/GeneratedCafitworkoutuikitthumb1Widget.dart';

/* Frame Cover
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCoverWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 800.0,
      height: 600.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 800.0,
              height: 600.0,
              child: GeneratedCafitworkoutuikitthumb1Widget(),
            )
          ]),
    ));
  }
}
