import 'package:flutter/material.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget/generated/GeneratedCalendar_duotoneWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget/generated/GeneratedGroupWidget4.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget/generated/GeneratedPremiumWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget/generated/Generated25008001501850Widget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget/generated/GeneratedGoodFoodExerciseRemainingWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget/generated/GeneratedChat_altWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget/generated/GeneratedCFA_RunningHistoryWidget1.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget/generated/GeneratedCaloriesWidget.dart';
import 'package:flutterapp/fitapp/generatedcfa_runninghistorywidget/generated/GeneratedMar13Mar19Widget.dart';

/* Frame CFA_Running-History
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCFA_RunningHistoryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedCFA_RunningHistoryWidget1(),
              ),
              Positioned(
                left: 117.0,
                top: 262.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 25.0,
                child: GeneratedMar13Mar19Widget(),
              ),
              Positioned(
                left: 289.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 23.0,
                child: GeneratedPremiumWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 116.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 125.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 149.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 30.0,
                child: GeneratedCaloriesWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 166.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 27.0,
                child: Generated25008001501850Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 20.0,
                child: GeneratedGoodFoodExerciseRemainingWidget(),
              ),
              Positioned(
                left: 132.0,
                top: 764.0,
                right: null,
                bottom: null,
                width: 23.441999435424805,
                height: 24.0,
                child: GeneratedGroupWidget4(),
              ),
              Positioned(
                left: 206.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 26.0,
                child: GeneratedChat_altWidget(),
              ),
              Positioned(
                left: 260.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 29.0,
                child: GeneratedCalendar_duotoneWidget(),
              )
            ]),
      ),
    ));
  }
}
